contracts/KyberConstants.sol
contracts/KyberNetwork.sol
contracts/KyberReserve.sol
contracts/KyberWallet.sol
contracts/MockExchange.sol
contracts/VolumeImbalanceRecorder.sol
contracts/Wrapper.sol

my mistake. didn't add my name in front of the contract.

Kyber constants

---

contracts/ExpectedRate.sol
contracts/FeeBurner.sol
contracts/KyberNetwork.sol
contracts/KyberReserve.sol
contracts/Pricing.sol
contracts/SanityPricing.sol
contracts/VolumeImbalanceRecorder.sol
contracts/mockContracts/MockExchange.sol
contracts/mockContracts/Wrapper.sol

some more coding style

---

scripts/deployment.js

this allow reserve deposit eth to exchange in simulation env

withdraw eth from reserve

---

contracts/KyberNetwork.sol

sorry. 
but my fixes of kyber network added one more solhint issue.
so need another pull...

solhint indent

---

test/conversionRate.js
test/expectedRate.js
test/feeBurner.js
test/helper.js
test/kyberNetwork.js
test/kyberReserve.js
test/permissionGroups.js
test/sanityRates.js
test/utils.js
test/volumeImbalanceRecorder.js
test/whitelist.js

with all new tests.
coverage run:
https://gist.github.com/ilanDoron/54bf64fbbe1b75ffc38f6ef9837e2fd9
coverage was run with 2 changes in code: (for coverage only)
1. removing two lines in default payable function in kyberNetwork.
2. in ERC20Interface. change from interface to contract.
following tests fail - fixes already exist in our new code:
some fail only in coverage run. due to modifications the coverage tool makes (4-5 out of 16).
167 passing (2m)
16 failing
1) Contract: ExpectedRates should test can't init expected rate with empty contracts (address 0).:
AssertionError: expected throw but got: AssertionError: throw was expected in line above.
at Context.<anonymous> (test/expectedRate.js:198:13)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)
2) …

Ilanadd tests

---

test/permissionGroups.js

new tests for new permissions group code

---

contracts/mockContracts/MockConversionRate.sol
test/conversionRate.js

you can commit the code change.
test approves!!

Add test to verify get rate when near max total imbalance

---

web3deployment/mainnet_production.json

please see all updated values.
especially chage in permissions.
operators for whitelist
alerters for reserve
admin for fee burner.

update values to match our mainnet deployment

---

web3deployment/mainnet_staging.json

Hi @yaronvel 
see staging json updates.
All as discussed on TG regarding staging.

update operators and admin addresses for staging deployment

---

deployment_input.json
scripts/deployment.js

- Add field 'internal use' to indicate token is supported by the internal reserve
- Add filed 'listed' to indicate token has been listed in the wallet

Update deployment_dev.json in simulation

---

contracts/previousContracts/KyberReserveV1.sol
web3deployment/mainnet_production.json
web3deployment/readVerifyDeployment.js

fix issues:
two contracts same name make truffle crash.
update expected rate permissions.

fix failing deployment

---

test/kyberNetwork.js

@yaronvel @ilanDoron please review

Adding await statements to tests.

---

contracts/MakerOrders.sol
contracts/Orders.sol
contracts/PermissionLessReserve.sol

The responsibility for keeping track of each makers free orders is
moved to a new layer that the PermissionLessReserve now extends.

Moving some functionality to MakerOrders contract

---

contracts/KyberNetwork.sol
contracts/permissionless/FeeBurnerResolver.sol
contracts/permissionless/OrderBookReserve.sol
contracts/permissionless/OrderBookReserveInterface.sol
contracts/permissionless/PermissionlessOrderBookReserveLister.sol
test/kyberNetwork.js
test/orderBookReserve.js
test/permissionlessOrderBookReserveLister.js

code review comments and adding fee burner resolver

---

contracts/permissionless/OrderBookReserve.sol
contracts/permissionless/Orders.sol
contracts/permissionless/OrdersInterface.sol
test/orders.js

Also some test ordering and renaming.

Orders: improving updateWithPositionHint to updateAmounts in case no move required

---

contracts/permissionless/Orders.sol
contracts/permissionless/OrdersInterface.sol
test/orders.js

- in updateWithPositionHint() reject if orderId is passed as prevId as well

Orderbook reserve tasks

---

scripts/get_liquidity_params.py
scripts/liquidity_input_params.json

Now get json file and supports several options.

Refactor liquidity params script.

---

test/orderList.js

Test that using removed orders for addAfterId and
updateWithPositionHint fails.

Order list: test for problematic use of removed orders

---

web3deployment/liquidityReserveDeployer.js
web3deployment/liquidityReserve_input.json

Fix for issue reported on #388.

Fixes to liquidityReserveDeployer.js script

---

test/kyberOasisReserve.js

Align oasis test to new web3 as used in uniswap test

---

README.md

Removed deadlink in README

---

contracts/ConversionRates2.sol
contracts/mockContracts/MockConversionRate2.sol
test/conversionRate2.js
test/expectedRate.js
test/kyberNetwork.js
test/kyberReserve.js

It is working in progress for step function enhancement feature
Fixed: https://github.com/KyberNetwork/smart-contracts/issues/291

[WIP] Add new conversion rate contract with step function enhancement

---

contracts/wethContracts/KyberWethReserve.sol
contracts/wethContracts/mockContracts/MockWeth.sol
test/helper.js
test/kyberWethReserve.js
web3deployment/wethReserveDeployer.js

Includes testing.
Also includes an addition in helper to make throw catching more neat.

Weth Reserve Implementation

---

test/liquidityConversionRate.js

- Has array of params, so new params can be added and run same tests
- Check buy/sell when fee is 0, we should never lose 
- Check can buy all (most) inventory, rate is between supported rates

Add new tests for apr conversion rate

---

test/v4/helper.js
test/v4/utils.js
test/v4/utils2.js
test/v4/utils3.js

I've also updated the packages.json with latest versions, and it's working for me. Please test.

Utils.js, Utils2.js, Utils3.js, update to web3 v1.2.4

---

contractsV5/IKyberHint.sol
contractsV5/KyberNetwork.sol
contractsV5/KyberNetworkProxy.sol

change hint type values.
do some changes in kyberNetwork

interface updates

---

contractsV5/IKyberTradeLogic.sol
contractsV5/KyberNetwork.sol
contractsV5/KyberTradeLogic.sol
test/v5/kyberTradeLogic.js

changing API for getRatesForToken
so it changes network and trade logic.
add draft file for testing trade logic.
but still not working

[WIP] add trade logic test

---

contractsV5/KyberHintHandler.sol
test/v5/kyberHintHandler.js

replaced separator
also added some numbers to reserve IDs
so many places 000000 --> 123456
so each easier to find separator.

change seperator opcode from 0x00 to 0x77

---

contractsV5/FeeHandler.sol

Some logics are wrong in fee handler, please see my changes

Fix some logics in fee handler

---

contractsV5/IKyberFeeHandler.sol
contractsV5/KyberFeeHandler.sol
contractsV5/KyberNetwork.sol
test/v5/kyberFeeHandler.js
test/v5/kyberNetwork.js
test/v5/networkHelper.js

accumulate fee per platform wallet.
enable claim

change platform wallet logic

---

contractsSol5/IKyberHint.sol
contractsSol5/KyberHintHandler.sol
contractsSol5/KyberTradeLogic.sol
test/sol5/kyberHintHandler.js

Modified KyberHintHandler.sol to add accurate failedIndex for incorrect hints.

Adding failedIndex for KyberHintHandler.sol

---

contractsSol5/PermissionGroups2.sol
contractsSol5/mock/MockPermissionGroups2.sol
test/sol5/permissionGroups2.js

* Minor contract bug fix, added PermGrps tests
* Add CRLF

Minor contract bug fix, added PermGrps tests (#710)

---

contractsSol5/KyberNetwork.sol
contractsSol5/utils/Withdrawable2.sol

change eth transfer calls.

---

contractsSol5/stakingAndDao/KyberDAO.sol
contractsSol5/stakingAndDao/mock/MockKyberDaoMoreGetters.sol
test/sol5/kyberDao.js
test/sol5/kyberProxyIntegration.js

The gas cost reduces around 3k-5k for the first trade of each epoch after removing the caching

Remove caching winning option data and bit trick for formula params

---

contractsSol5/KyberMatchingEngine.sol
contractsSol5/KyberNetwork.sol
contractsSol5/stakingAndDao/KyberDAO.sol
test/sol5/kyberDao.js

add overflow checks.
matching engine tests without assumptions that BPS values are < BPS
so some extra checks.

Add overflow checks

---

contractsSol5/IKyberMatchingEngine.sol
contractsSol5/IKyberStorage.sol
contractsSol5/KyberMatchingEngine.sol
contractsSol5/KyberNetwork.sol
contractsSol5/KyberStorage.sol
contractsSol5/mock/MockNetwork.sol
contractsSol5/utils/Utils4.sol
contractsSol5/wrappers/KyberRateHelper.sol
test/sol5/kyberNetwork.js
test/sol5/kyberNetworkProxy.js
test/sol5/networkHelper.js

it seemed like solidity compiles.
but it didn't
had circular include statements.
and had un implemented functions.

fix solidity to compile, fix some tests

---

contractsSol5/KyberNetwork.sol
contractsSol5/KyberNetworkProxy.sol
contractsSol5/mock/MaliciousKyberNetwork.sol
test/sol5/kyberNetworkProxy.js

- Recalc actualSrcWei
- Fix trailing whitespaces
- KNP tests fixed

Fix KNP tests

---

test/sol5/kyberNetwork.js

moving the split check to a new describe - misc
fixing wrong contract init

fix a few tests

---

contractsSol5/Dao/KyberFeeHandler.sol
contractsSol5/Dao/mock/MockContractCallBurnKNC.sol
contractsSol5/IKyberMatchingEngine.sol
contractsSol5/KyberMatchingEngine.sol
contractsSol5/KyberNetwork.sol
contractsSol5/KyberNetworkProxy.sol
contractsSol5/KyberStorage.sol
contractsSol5/mock/GenerousKyberNetwork.sol
contractsSol5/mock/GenerousKyberNetwork2.sol
contractsSol5/mock/MaliciousKyberNetwork.sol
contractsSol5/mock/OtherMatchingEngine.sol
contractsSol5/wrappers/KyberRateHelper.sol
test/sol4/kyberProxyV1.js
test/sol5/kyberFeeHandler.js
test/sol5/kyberMatchingEngine.js
test/sol5/kyberNetwork.js
test/sol5/kyberNetworkProxy.js
test/sol5/kyberStorage.js
test/sol5/networkHelper.js

https://trello.com/c/ICYc1MJn/74-renaming-in-code
- network reference standardized to "kyberNetwork"
- storage reference standardized to "kyberStorage"
- updating contracts will be "ContractUpdated(Interface newContractAddress)"

Code rename

---

contractsSol5/Dao/EpochUtils.sol
contractsSol5/Dao/IKyberStaking.sol
contractsSol5/Dao/KyberDAO.sol
contractsSol5/Dao/KyberFeeHandler.sol
contractsSol5/Dao/KyberStaking.sol
contractsSol5/Dao/mock/MockKyberDAOTestHandleWithdrawal.sol
contractsSol5/Dao/mock/MockKyberDaoMoreGetters.sol
contractsSol5/Dao/mock/MockKyberDaoWithdrawFailed.sol
contractsSol5/Dao/mock/MockKyberStakingMalicious.sol
contractsSol5/Dao/mock/MockMaliciousDAO.sol
contractsSol5/Dao/mock/MockMaliciousDaoReentrancy.sol
contractsSol5/Dao/mock/MockStakingContract.sol
contractsSol5/IKyberDAO.sol
contractsSol5/mock/MaliciousDAO.sol
contractsSol5/mock/MockDAO.sol
test/sol5/kyberDao.js
test/sol5/kyberIntegration.js
test/sol5/kyberStaking.js

Changes:
1. Using struct for staker's latest data + staker's data per epoch in KyberStaking, campaign and vote data in KyberDAO
2. Remove code duplication for get latest network or brr data
3. Fix naming convention and style
Can check each commit changes

Update Staking and DAO according to audit feedbacks

---

contractsSol5/IKyberStorage.sol

..... Can't believe we missed this =/
We imported a whole contract instead of an interface in the network contract..... Should see bytecode size reduction, I think

Contract -> Interface

---

test/sol4/kyberProxyV1.js

- Failing tests have to do with MaliciousNetwork. If it "steals" funds by sending the user less than expected, and reports that amount, then the check that `require(reportedDestAmount == tradeOutcome.userDeltaDestAmount);` in the proxy will still be true...

Fixed most failing tests, except 2

---

.solcover.js
contracts/sol6/Dao/KyberDAO.sol
contracts/sol6/Dao/KyberFeeHandler.sol

- Move permission logic into DAO and fee contracts
- Exclude mock files from coverage

Coverage Run Fix

---

README.md

I am trying to be clear for external developers using this repo
which APIs are for public use.
and which are internal
for internal ones we might change every version.
public facing API we should maintain as much as possible.
also fixing some changes related to sol6 changes

update public facing interfaces in readme file

---

contracts/sol6/IKyberNetwork.sol
contracts/sol6/IKyberNetworkProxy.sol
contracts/sol6/KyberNetwork.sol
contracts/sol6/KyberNetworkProxy.sol
contracts/sol6/mock/SimpleKyberProxy.sol
test/sol6/kyberNetwork.js
test/sol6/kyberNetworkProxy.js
test/sol6/networkHelper.js

Cannot work if maxDestAmount is used though....

Removed rateWithoutFees and getPriceDataNoFees, updated rateWithNetworkFee calculation

---

contracts/sol6/KyberNetwork.sol
test/sol6/kyberNetwork.js
test/sol6/networkHelper.js

When doing reverse calculation:
- new src amounts are used only when any of them isn't greater then corresponding current srcAmount.
- If newTradeWei > tradeWei, fallback to use tradeWei.

Fix reverse amount calculation for trades. When maxDestAmount is small and we recalculate trade values in reverse.

---

contracts/sol6/KyberNetwork.sol
test/sol6/kyberNetwork.js

This PR should wait till we finalize overflow session
any overflow checks or comments should be added here.

add overflow check at calcTradeSrcAmount

---

contracts/sol6/Dao/KyberFeeHandler.sol
test/sol6/kyberFeeHandler.js
test/sol6/kyberIntegration.js

FeeHandler:
- Enable updating network proxy.
- Setting network address without proxy.

Enable updating network proxy and setting network address in FeeHandler

---

contracts/sol6/IKyberHint.sol
contracts/sol6/KyberHintHandler.sol
contracts/sol6/KyberMatchingEngine.sol
contracts/sol6/mock/MockHintHandler.sol
test/helper.js
test/sol6/kyberHintHandler.js
test/sol6/kyberMatchingEngine.js
test/sol6/kyberNetwork.js
test/sol6/networkHelper.js

Other improvements: MaskOut trade type with empty reserveId list is valid

Validate that token is listed for reserve in KyberHintHandler

---

contracts/sol6/Dao/KyberDao.sol
contracts/sol6/KyberMatchingEngine.sol
contracts/sol6/KyberNetwork.sol
contracts/sol6/KyberStorage.sol
test/sol6/kyberDao.js
test/sol6/kyberStorage.js

- remove unused parameter
- remove unused import.
- fix revert message

fix audit comments from iteration 2 by Chain Security

---

contracts/sol6/Dao/KyberFeeHandler.sol
contracts/sol6/KyberNetwork.sol
solcOptimiserSettings.js
test/sol6/kyberFeeHandler.js
test/sol6/kyberNetwork.js

Reverts KyberNetwork/smart-contracts#1037

Revert "Katalyst last changes into katalyst audit iteration #4"

---

contracts/sol6/Dao/emergency/EmergencyFeeHandler.sol
test/sol6/emergencyFeeHandler.js
test/sol6/kyberFeeHandler.js

- update emergency fee handler
- update test case when total rebateBpsPerWallet is not BPS

update emergency fee handler

---

package-lock.json
package.json
web3deployment/KatalystDeploy/Katalyst_deploy_production_input.json
web3deployment/KatalystDeploy/Katalyst_deploy_rinkeby_input.json
web3deployment/KatalystDeploy/Katalyst_deploy_staging_input.json
web3deployment/KatalystDeploy/katalystNetworkDeployer.js
web3deployment/KatalystDeploy/listTokens.js
web3deployment/KatalystDeploy/monitorAndListTokens.js
web3deployment/helpers/gasStation.js

* Added input json files used for Rinkeby, staging and production deployment
* Updated deployer script, added token listing scripts

Update Katalyst deployment input and script
