KyberNetwork/smart-contracts

- contracts/ConversionRates.sol
- contracts/ConversionRatesInterface.sol
- contracts/ExpectedRate.sol
- contracts/ExpectedRateInterface.sol
- contracts/FeeBurner.sol
- contracts/FeeBurnerInterface.sol
- contracts/KyberNetwork.sol
- contracts/KyberReserve.sol
- contracts/KyberReserveInterface.sol
- contracts/SanityRates.sol
- contracts/SanityRatesInterface.sol
- contracts/WhiteList.sol
- contracts/WhiteListInterface.sol
- contracts/mockContracts/MockImbalanceRecorder.sol
adding interface to all upgradable contracts.
This will allow upgrading them without a need to change the binary of an unchanged contract.
Hence, it will be possible to use same deployed binaries when testing upgrades.
For example, if we change `KyberReserve.sol`, the binary of `KyberNetwork.sol` would have been change before.
As a result the deployed `KyberNetwork.sol` would have different binary than the one we use for testing.
> adding interface to all upgradable contracts

- test/helper.js
- test/liquidityFormula.js
This is so we can use these functions in other places as well, e.g in liquidity
conversion rate test.
> liquidity: Move functions from liquidity formula test to helper.

- .gitattributes
This helps make browsing code on GitHub much more pleasant. (More info [here](https://medium.com/@danielque/psa-how-to-fix-githubs-syntax-highlighting-for-solidity-4e9867c540b6).)
> Configure Solidity syntax highlighting

- contracts/permissionless/OrderList.sol
Indicate deleted orders by setting their prev to TAIL and their next to 
HEAD.
Use this indication to refuse accepting them as hints.
> OrderList: mark and detect deleted orders

- contracts/permissionless/OrderList.sol
- test/orderList.js
Test that using removed orders for addAfterId and
updateWithPositionHint fails.
> Order list: test for problematic use of removed orders

- contracts/ExpectedRate.sol
- contracts/FeeBurner.sol
- test/expectedRate.js
- test/feeBurner.js
- test/kyberNetwork.js
Reverts KyberNetwork/smart-contracts#433
was decided not to include this in next deploy
will be delayed.
> Revert "Arbitrage check shifted to FeeBurner"

- contractsV5/IKyberTradeLogic.sol
- contractsV5/KyberNetwork.sol
- contractsV5/KyberTradeLogic.sol
- test/v4/helper.js
- test/v5/kyberNetwork.js
- test/v5/kyberNetworkProxy.js
- test/v5/kyberTradeLogic.js
- test/v5/networkHelper.js
- Remove overwriting of reserveInstances in networkHelper
- Split optionalAmount to optionalBuy and optionalSell amounts
- Use `BN.gte` instead of `>=` for comparison in helper
- Modify getRatesForToken function to reflect rate with network fee
- Added TradeLogic tests
> [WIP] Add Trade Logic Tests

- web3deployment/reserveDeployer.js
Minor fix to reserveDeployer.js script due to ConversionRates not compiling as reported by one of the token teams during onboarding.
> Minor fix to reserveDeployer.js script

- contractsSol5/KyberNetwork.sol
- test/sol5/kyberNetwork.js
Because of the stack too deep issue, I cannot instantiate another variable inside `getExpectedRateWithHintAndFee` to modify srcQty.
I thought I could do the fix in the local `calcRatesAndAmounts` function, but both `getExpectedRate` functions need the modified srcQty when calculating rates, so that doesn't work either.
I definitely cannot modify in the `initTradeInput`, because that's being used by the tradeWithHint functions, and the verification of `srcQty != 0` is done after this function.
Only workaround I'm left with, is to change `getExpectedRateWithHintAndFee` to public, so that I can modify srcQty directly.
> zero srcQty handling

- contractsSol5/KyberNetwork.sol
gas helper call at end of flow has 2 advantages.
1. amounts are updated (after max dest amount calc).
2. burning gas tokens cost gas . the gas payback is only after all Tx is done. if not enough gas left to burn tokens, we should avoid burn since it can cause revert.
>  move gas helper call to end of trade flow

- contractsSol5/Dao/KyberDAO.sol
- contractsSol5/Dao/KyberStaking.sol
- contractsSol5/Dao/mock/MockKyberDAOTestHandleWithdrawal.sol
- contractsSol5/Dao/mock/MockKyberDaoWithdrawFailed.sol
- contractsSol5/Dao/mock/MockKyberStakingMalicious.sol
- contractsSol5/Dao/mock/MockMaliciousDaoReentrancy.sol
- contractsSol5/IKyberDAO.sol
- contractsSol5/mock/MockDAO.sol
- test/sol5/kyberDao.js
- test/sol5/kyberIntegration.js
- test/sol5/kyberStaking.js
Current with withdraw function has complex logics updating data in Staking and Dao contract
We want to allow staker withdraws their stake even if something is wrong with DAO or updating data in Staking, only need to check if staker's latest stake >= withdrawal amount
> Simplify withdrawal logics to allow staker withdraw

- contractsSol5/KyberNetwork.sol
bytecode size diff
after this change: 23376
before this change: 23369
gas
for split before:
2e: 541075 gas used, type: SPLIT fee: 123 num reserves: 3
e2t: 531420 gas used, type: SPLIT fee: 123 num reserves: 3
t2t: 921553 gas used, type: SPLIT fee: 123 num reserves: 3
after: 
t2e: 540689 gas used, type: SPLIT fee: 123 num reserves: 3
e2t: 531074 gas used, type: SPLIT fee: 123 num reserves: 3
t2t: 920821 gas used, type: SPLIT fee: 123 num reserves: 3
non split before:
t2e: 478351 gas used, type: NO HINT fee: 123 num reserves: 3
e2t: 519036 gas used, type: NO HINT fee: 123 num reserves: 3
t2t: 878734 gas used, type: NO HINT fee: 123 num reserves: 3
after:
t2e: 478359 gas used, type: NO HINT fee: 123 num reserves: 3
e2t: 519044 gas used, type: NO HINT fee: 123 num reserves: 3
t2t: 878750 gas …
> small improvement for split trades. when calculating destAmount 

- contracts/sol6/KyberNetwork.sol
- contracts/sol6/KyberStorage.sol
- test/sol6/kyberNetwork.js
- test/sol6/kyberStorage.js
the network should be able to work without any DAO connected.
so in the case of an issue with the DAO contract. we would like to enable setting DAO Address to 0
> enable setting DAO Address to 0.

- contracts/sol6/KyberNetwork.sol
- Move `handleChange` to end of trade flow, so that `handleChange` not trigger any rate change before doReserveTrade
> Move handleChange to end of trade flow

- contracts/sol6/KyberStorage.sol
- test/sol6/kyberStorage.js
- Mappings `srcTokensPerReserve` and `destTokensPerReserve`
- `getListedTokensByReserveId()` and `getListedTokensByReserveAddress()`
- `delistTokensOfReserve` to automatically delist all tokens when removing reserve
> Auto delist tokens when removing reserve

- contracts/sol6/IKyberStorage.sol
- contracts/sol6/KyberNetwork.sol
- contracts/sol6/KyberStorage.sol
- contracts/sol6/mock/GenerousKyberNetwork.sol
- contracts/sol6/mock/GenerousKyberNetwork2.sol
- contracts/sol6/mock/MaliciousKyberNetwork.sol
- contracts/sol6/mock/MaliciousStorage.sol
- test/sol4/kyberProxyV1.js
- test/sol6/kyberNetwork.js
- test/sol6/kyberStorage.js
What did this PR do:
- validate if reserve is listed for token (for maskIn, Split trades)
- better revert msg if network return 0 rate
- network validate input when getExpectedRate
Checklist:
Gas report
```
┌─────────────────────────────────────────────────────────┬──────────┬─────────┬───────┐
│                         (index)                         │ Katalyst │ current │ diff  │
├─────────────────────────────────────────────────────────┼──────────┼─────────┼───────┤
│      t2e trade, type: SPLIT, fee: 123, reserves: 3      │  576101  │ 579550  │ 3449  │
│      e2t trade, type: SPLIT, fee: 123, reserves: 3      │  561132  │ 564591  │ 3459  │
│      t2t trade, type: SPLIT, fee: 123, reserves: 3      │  979449  │ 986706  │ 7257  │
│     t2e trade, type: NO HINT, fee: 123, reserves: 3 …
```
> storage validate if reserve is listed for token

- contracts/sol6/Dao/IKyberStaking.sol
- contracts/sol6/Dao/KyberDAO.sol
- contracts/sol6/Dao/KyberStaking.sol
- contracts/sol6/Dao/mock/MockStakingContract.sol
- contracts/sol6/wrappers/KyberRateHelper.sol
- test/sol6/kyberDao.js
- test/sol6/kyberStaking.js
This PR does following changes:
- KyberDao: Move all validations to validateCampaignParams when submit new campaign
- KyberDao: Avoid incompatible startTimestamp and startEpoch in validateCampaignParams function
- KyberDao: Make sure cInPrecision < 2^128 and tInPrecision < 2^128
- KyberStaking: Add functions to get all latest + per epoch data for a staker
- KyberStaking: Update function name for getting raw staker per epoch data
- KyberStaking: Change delegatedAddress -> representative
> Update campaign validation logics in KyberDao, add more get functions in KyberStaking

- contracts/sol6/Dao/KyberFeeHandler.sol
- contracts/sol6/IKyberFeeHandler.sol
- contracts/sol6/mock/ReentrancyFeeClaimer.sol
- test/sol6/kyberFeeHandler.js
Case:
- The platform has the fee of 5 wei
- call **claimPlatformFee** -> receive 4 wei
- trigger callback function -> Earn some more platform fees
- PlatformFeePaid emitted.
-> platform fee is not reset to 1
In this PR:
- add reentrancy guard to claimPlatformFee, handleFees, claimReserveRebate
- add claimPlatformFee to IKyberFeeHandler
> set reentrancy block when call trade during claim platformFee and rebate

- contracts/sol6/Dao/EmergencyFeeHandler.sol
- contracts/sol6/Dao/emergency/EmergencyFeeHandler.sol
- contracts/sol6/Dao/mock/MockEmergencyFeeHandler.sol
- package-lock.json
- package.json
- test/sol6/emergencyFeeHandler.js
This PR create an emergency fee handler handling the fee when FeeHandler is unavailable (bug,..)
- Keep track of platformFee and allow to claimPlatformFee
- Keep track of rebatePerWallet and totalRewardWei, but not allow to claim rebate fee and reward
- Admin can withdraw to distribute the reward and fee but no more than totalBalance - totalPlatformFee
> add EmergencyFeeHandler

- contracts/sol6/KyberNetwork.sol
- contracts/sol6/utils/Utils5.sol
- test/helper.js
- test/sol6/kyberNetwork.js
When trying to list COMP token (compound) we found we can't use approve(2**255)
has this code in approve function:
function approve(address spender, uint rawAmount) external returns (bool) {
uint96 amount;
if (rawAmount == uint(-1)) {
amount = uint96(-1);
} else {
amount = safe96(rawAmount, "Comp::approve: amount exceeds 96 bits");
}
allowances[msg.sender][spender] = amount;
emit Approval(msg.sender, spender, amount);
return true;
}
> update token.approve to max allowance in kyberNetwork contract. from '2**255' to '2*256-1'
